-- this example file was generated by claude sonnet 4.6
local Library = loadstring(game:HttpGet(
    "https://raw.githubusercontent.com/ArchIsDead/vita-ui-modified/refs/heads/main/source.lua"
))()

local Cfg  = Library.Cfg
local Exec = Library.Exec

local function N(title, desc, color, dur)
    Library:Notification({ Title=title, Desc=desc or "", Color=color or "#6495ED", Duration=dur or 3 })
end

local Window = Library:Window({
    Title            = "Skid Playground",
    SubTitle         = "Damn.",
    ToggleKey        = Enum.KeyCode.RightControl,
    Icon             = "rbxassetid://104055321996495",
    ToggleIcon       = "rbxassetid://104055321996495",
    ToggleBtnCorner  = UDim.new(1, 0),
    FolderName       = "SkidPlayground",
    AutoLoad         = function(name, data)
        N("Restored", name, "#50C864", 3)
    end,
    AutoScale = true,
    Scale     = 1.45,
    Theme = {
        Accent       = "#FF007F",
        Background   = "#0B0B0B",
        Row          = "#121212",
        RowAlt       = "#0D0D0D",
        Stroke       = "#202020",
        Text         = "#EBEBEB",
        SubText      = "#949494",
        TabBg        = "#0D0D0D",
        TabStroke    = "#4B0026",
        TabImage     = "#FF007F",
        DropBg       = "#101010",
        ToggleBg     = "#0B0B0B",
        Font         = Enum.Font.Gotham,
        FontBold     = Enum.Font.GothamBold,
        FontMedium   = Enum.Font.GothamMedium,
        CornerRadius = UDim.new(0, 5),
    },
})

Library:SetExtraTitle("R4")
Library:SetExtraSubTitle("is tuff")


local P_Tog = Window:NewPage({
    Title         = "Toggles",
    Desc          = "Toggle element tests",
    Icon          = "toggle-left",
    TabImageColor = "#FF007F",
})

P_Tog:Section("Basic toggles")

local tog_round = P_Tog:Toggle({
    Title        = "Round toggle",
    Desc         = "CornerRadius = UDim.new(1,0)",
    Value        = false,
    id           = "tog_round",
    CornerRadius = UDim.new(1, 0),
    Callback     = function(v) N("Round", tostring(v)) end,
})

local tog_square = P_Tog:Toggle({
    Title        = "Square toggle",
    Desc         = "CornerRadius = UDim.new(0,0)",
    Value        = true,
    id           = "tog_square",
    CornerRadius = UDim.new(0, 0),
    Callback     = function(v) N("Square", tostring(v)) end,
})

local tog_soft = P_Tog:Toggle({
    Title        = "Soft square",
    Desc         = "CornerRadius = UDim.new(0,4)",
    Value        = false,
    id           = "tog_soft",
    CornerRadius = UDim.new(0, 4),
    Callback     = function(v) N("Soft", tostring(v)) end,
})

P_Tog:Divider()
P_Tog:Section("Custom icon toggle")

local tog_icon = P_Tog:Toggle({
    Title        = "Toggle with custom icon",
    Desc         = "Icon shows when enabled",
    Value        = false,
    id           = "tog_icon",
    CornerRadius = UDim.new(1, 0),
    Icon         = "rbxassetid://104055321996495",
    Callback     = function(v) N("Custom icon toggle", tostring(v)) end,
})

P_Tog:Button({
    Title    = "Change icon at runtime",
    Desc     = "Calls :SetIcon() on the toggle above",
    Text     = "Set icon",
    Callback = function() tog_icon:SetIcon("rbxassetid://104055321996495") N("Icon","Set") end,
})

P_Tog:Divider()
P_Tog:Section("Enable / Disable")

local tog_dis = P_Tog:Toggle({
    Title   = "Disabled toggle",
    Desc    = "Starts disabled, click buttons below",
    Value   = false,
    id      = "tog_dis",
    Enabled = false,
    Callback = function(v) end,
})

P_Tog:MultiButton({
    Buttons = {
        { Text="Enable",  Color="#50C864", Callback=function() tog_dis:Enable();  N("Toggle","Enabled","#50C864") end },
        { Text="Disable", Color="#DC3232", Callback=function() tog_dis:Disable(); N("Toggle","Disabled","#DC3232") end },
        { Text="Flip",                     Callback=function() tog_round:SetValue(not tog_round:GetValue()) end },
        { Text="Hide",                     Callback=function() tog_soft:SetVisible(false) end },
        { Text="Show",                     Callback=function() tog_soft:SetVisible(true) end },
    },
})


local P_Sli = Window:NewPage({
    Title         = "Sliders",
    Desc          = "Slider element tests",
    Icon          = "sliders",
    TabImageColor = "#0088FF",
})

P_Sli:Section("Slider types")

local sli_int = P_Sli:Slider({
    Title    = "Integer slider",
    Desc     = "Rounding = 0",
    Min      = 0, Max = 100, Value = 50,
    Rounding = 0, Suffix = " pts",
    id       = "sli_int",
    Callback = function(v) end,
})

local sli_dec = P_Sli:Slider({
    Title    = "Decimal slider",
    Desc     = "Rounding = 2",
    Min      = 0, Max = 1, Value = 0.5,
    Rounding = 2,
    id       = "sli_dec",
    Callback = function(v) end,
})

local sli_neg = P_Sli:Slider({
    Title    = "Negative range",
    Desc     = "Min = -50, Max = 50",
    Min      = -50, Max = 50, Value = 0,
    Rounding = 0,
    id       = "sli_neg",
    Callback = function(v) end,
})

P_Sli:MultiButton({
    Title   = "Read / control",
    Buttons = {
        { Text="Read all",  Callback=function() N("Values", sli_int:GetValue().." | "..sli_dec:GetValue().." | "..sli_neg:GetValue()) end },
        { Text="Set to max", Callback=function() sli_int:SetValue(100); sli_dec:SetValue(1); sli_neg:SetValue(50) end },
        { Text="Reset",      Callback=function() sli_int:SetValue(50); sli_dec:SetValue(0.5); sli_neg:SetValue(0) end },
    },
})

P_Sli:Divider()
P_Sli:Section("Progress bars")

local pb1 = P_Sli:Progress({ Title="Load",   Value=0,   Max=100, Suffix="%" })
local pb2 = P_Sli:Progress({ Title="Health", Value=100, Max=100, Suffix=" hp", Color="#50C864" })
local pb3 = P_Sli:Progress({ Title="Ammo",   Value=30,  Max=30,  Suffix=" / 30", Color="#0088FF" })

P_Sli:MultiButton({
    Buttons = {
        { Text="Fill",   Color="#50C864", Callback=function() pb1:SetValue(100); pb2:SetValue(100); pb3:SetValue(30) end },
        { Text="Half",                    Callback=function() pb1:SetValue(50); pb2:SetValue(50); pb3:SetValue(15) end },
        { Text="Empty",  Color="#DC3232", Callback=function() pb1:SetValue(0); pb2:SetValue(0); pb3:SetValue(0) end },
        { Text="Random",                  Callback=function()
            pb1:SetValue(math.random(0,100)); pb2:SetValue(math.random(0,100)); pb3:SetValue(math.random(0,30))
        end },
    },
})


local P_Inp = Window:NewPage({
    Title         = "Inputs",
    Desc          = "Input & keybind tests",
    Icon          = "type",
    TabImageColor = "#00CC66",
})

P_Inp:Section("Input fields")

local inp1 = P_Inp:Input({
    Title       = "With clipboard copy button",
    Placeholder = "Type something...",
    ShowButton  = Exec.clipboard,
    id          = "inp1",
    Callback    = function(v) N("Input 1", v) end,
})

local inp2 = P_Inp:Input({
    Title         = "Clear on submit",
    Placeholder   = "Clears after Enter...",
    ClearOnSubmit = true,
    id            = "inp2",
    Callback      = function(v) N("Submitted", v) end,
})

local inp3 = P_Inp:Input({
    Title       = "No copy button",
    Placeholder = "Plain input...",
    ShowButton  = false,
    id          = "inp3",
    Callback    = function(v) end,
})

P_Inp:MultiButton({
    Buttons = {
        { Text="Read all", Callback=function() N("Inputs", inp1:GetValue().." | "..inp2:GetValue().." | "..inp3:GetValue()) end },
        { Text="Set inp1", Callback=function() inp1:SetValue("Hello") end },
        { Text="Clear",    Callback=function() inp1:SetValue(""); inp2:SetValue(""); inp3:SetValue("") end },
    },
})

P_Inp:Divider()
P_Inp:Section("Keybinds")

local key1 = P_Inp:Keybind({
    Title    = "Keybind A",
    Desc     = "Click to rebind, then press any key",
    Value    = Enum.KeyCode.H,
    id       = "key1",
    Callback = function(k) N("Key A fired", k.Name) end,
})

local key2 = P_Inp:Keybind({
    Title    = "Keybind B",
    Desc     = "Flips Round toggle when pressed",
    Value    = Enum.KeyCode.J,
    id       = "key2",
    Callback = function() tog_round:SetValue(not tog_round:GetValue()) end,
})

P_Inp:Button({
    Title    = "Read keybinds",
    Text     = "Read",
    Callback = function() N("Keys", key1:GetValue().Name.." | "..key2:GetValue().Name) end,
})


local P_Drop = Window:NewPage({
    Title         = "Dropdowns",
    Desc          = "Dropdown element tests",
    Icon          = "chevron-down",
    TabImageColor = "#9955FF",
})

P_Drop:Section("Single select")

local drop1 = P_Drop:Dropdown({
    Title    = "Pick a color",
    List     = { "Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet" },
    Value    = "Red",
    id       = "drop1",
    Callback = function(v) N("Color", v) end,
})

local drop2 = P_Drop:Dropdown({
    Title    = "Pick a number",
    List     = { "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten" },
    Value    = "One",
    id       = "drop2",
    Callback = function(v) N("Number", v) end,
})

P_Drop:MultiButton({
    Buttons = {
        { Text="Read drop1", Callback=function() N("Drop1", tostring(drop1:GetValue())) end },
        { Text="Reset drop1", Callback=function() drop1:SetValue("Red") end },
        { Text="Add item", Callback=function() drop1:AddList("Extra") N("Added","Extra to drop1") end },
    },
})

P_Drop:Divider()
P_Drop:Section("Multi select")

local drop3 = P_Drop:Dropdown({
    Title    = "Pick multiple fruits",
    List     = { "Apple", "Banana", "Cherry", "Durian", "Elderberry", "Fig", "Grape" },
    Value    = { "Apple", "Banana" },
    id       = "drop3",
    Callback = function(v) N("Fruits", table.concat(v, ", ")) end,
})

P_Drop:MultiButton({
    Buttons = {
        { Text="Read multi",  Callback=function()
            local v = drop3:GetValue()
            N("Multi", type(v)=="table" and table.concat(v,", ") or tostring(v))
        end },
        { Text="Clear multi", Color="#DC3232", Callback=function() drop3:Clear() end },
    },
})


local P_Disp = Window:NewPage({
    Title         = "Display",
    Desc          = "All display elements",
    Icon          = "layout",
    TabImageColor = "#CC9900",
})

P_Disp:Section("Labels")

P_Disp:Label({ Title="Static label", Desc="Read-only text, no interaction" })
P_Disp:Label({ Title="<b>Rich text</b> in label", Desc="<i>Italic desc</i> with <font color=\"rgb(100,200,255)\">colored text</font>" })

local rl1 = P_Disp:RightLabel({ Title="Executor",  Right=Exec.name })
local rl2 = P_Disp:RightLabel({ Title="Clipboard", Right=tostring(Exec.clipboard) })
local rl3 = P_Disp:RightLabel({ Title="Live count", Right="0" })

do
    local count = 0
    task.spawn(function()
        while task.wait(1) do
            count = count + 1
            rl3:SetRight(tostring(count))
        end
    end)
end

P_Disp:Divider()
P_Disp:Section("Paragraphs")

P_Disp:Paragraph({
    Title = "Basic paragraph",
    Desc  = "A styled block of text. Supports <b>bold</b>, <i>italic</i>, and color.",
})

P_Disp:Paragraph({
    Title   = "Paragraph with buttons",
    Desc    = "An optional row of action buttons at the bottom of the paragraph.",
    Buttons = {
        { Text="Accept", Color="#50C864", Callback=function() N("Accepted","","#50C864") end },
        { Text="Decline", Color="#DC3232", Callback=function() N("Declined","","#DC3232") end },
        { Text="Ignore", Callback=function() N("Ignored") end },
    },
})

P_Disp:Divider()
P_Disp:Section("Banner")

P_Disp:Banner({ Image="rbxassetid://104055321996495", Height=100 })

P_Disp:Divider()
P_Disp:Section("Popups & Dialogs")

P_Disp:MultiButton({
    Buttons = {
        { Text="Popup",  Callback=function()
            Window:Popup({
                Title   = "Popup",
                Desc    = "A modal dialog with custom buttons.",
                Buttons = {
                    { Text="Confirm", Style="main", Callback=function() N("Confirmed","","#50C864") end },
                    { Text="Cancel",  Style="alt",  Callback=function() N("Cancelled") end },
                },
            })
        end },
        { Text="Dialog", Callback=function()
            Window:Dialog({
                Title="Dialog", Desc="Quick confirm or cancel.",
                ConfirmText="Yes", CancelText="No",
                OnConfirm=function() N("Yes","","#50C864") end,
                OnCancel=function() N("No") end,
            })
        end },
    },
})


local P_Cfg = Window:NewPage({
    Title         = "Config",
    Desc          = "Config system tests",
    Icon          = "save",
    TabImageColor = "#888888",
})

P_Cfg:Section("Config manager")

local cfgDrop = P_Cfg:Dropdown({
    Title="Saved configs", List=Cfg:listcfg(), Placeholder="Select config...",
    Callback=function(v) end,
})

local function RefreshDrop()
    cfgDrop:SetList(Cfg:listcfg())
    if Cfg:ActiveCfg() then cfgDrop:SetValue(Cfg:ActiveCfg()) end
end

local cfgName = P_Cfg:Input({
    Title="Config name", Placeholder="Enter name...", ShowButton=false,
})

P_Cfg:MultiButton({
    Buttons = {
        { Text="Create", Color="#50C864", Callback=function()
            local n=cfgName:GetValue(); if n=="" then N("Config","Enter a name","#FFA500"); return end
            if not Cfg:addcfg(n) then N("Config","Exists","#FFA500"); return end
            RefreshDrop(); N("Created",'"'..n..'"',"#50C864")
        end },
        { Text="Save", Callback=function()
            local n=cfgDrop:GetValue() or cfgName:GetValue()
            if not n or n=="" then N("Config","Select or name first","#FFA500"); return end
            Cfg:updcfg(n); RefreshDrop(); N("Saved",'"'..n..'"',"#50C864")
        end },
        { Text="Load", Color="#0088FF", Callback=function()
            local n=cfgDrop:GetValue() or cfgName:GetValue()
            if not n or n=="" then N("Config","Select first","#FFA500"); return end
            if Cfg:loadcfg(n) then N("Loaded",'"'..n..'"',"#50C864")
            else N("Error","Not found","#DC3232") end
        end },
        { Text="Del", Color="#DC3232", Callback=function()
            local n=cfgDrop:GetValue() or cfgName:GetValue(); if not n or n=="" then return end
            Window:Dialog({ Title="Delete", Desc='Delete "'..n..'"?', ConfirmText="Delete", CancelText="Cancel",
                OnConfirm=function() Cfg:delcfg(n); RefreshDrop(); N("Deleted",'"'..n..'"') end })
        end },
    },
})

P_Cfg:Divider()
P_Cfg:Section("Import / Export")

local cfgExportIn = P_Cfg:Input({ Title="Export JSON", Placeholder="Click Export...", ShowButton=Exec.clipboard })

P_Cfg:MultiButton({
    Buttons = {
        { Text="Export", Color="#50C864", Callback=function()
            local j = Cfg:exportcfg()
            if j then cfgExportIn:SetValue(j); N("Exported","JSON ready","#50C864")
            else N("Error","No active config","#DC3232") end
        end },
        { Text="Import", Color="#0088FF", Callback=function()
            local name = cfgName:GetValue(); local j = cfgExportIn:GetValue()
            if name=="" or j=="" then N("Import","Enter name and JSON","#FFA500"); return end
            if Cfg:importcfg(name, j) then RefreshDrop(); N("Imported",'"'..name..'"',"#50C864")
            else N("Error","Invalid JSON","#DC3232") end
        end },
    },
})

P_Cfg:Divider()
P_Cfg:Section("Auto load")

P_Cfg:MultiButton({
    Buttons = {
        { Text="Pin auto-load", Color="#50C864", Callback=function()
            local n=cfgDrop:GetValue(); if not n or n=="" then N("Config","Select first","#FFA500"); return end
            Cfg:setautoload(n); N("Auto-load",'"'..n..'" loads next run',"#50C864")
        end },
        { Text="Clear pin", Color="#FF6600", Callback=function() Cfg:clearautoload(); N("Auto-load","Cleared") end },
    },
})

P_Cfg:Divider()
P_Cfg:RightLabel({ Title="Active",  Right=Cfg:ActiveCfg() or "none" })
P_Cfg:RightLabel({ Title="Folder",  Right=Cfg:GetFolder() })
P_Cfg:RightLabel({ Title="Configs", Right=tostring(#Cfg:listcfg()) })


local P_Set = Window:NewPage({
    Title         = "Settings",
    Desc          = "UI, theme & notifications",
    Icon          = "settings",
    TabImageColor = "#444444",
})

P_Set:Section("Interface")

Library:AddSizeSlider(P_Set)

P_Set:Divider()
P_Set:Section("Toggle key")

local dropToggleKey = P_Set:Dropdown({
    Title    = "Toggle key",
    Desc     = "Key to show/hide the UI",
    List     = { "RightControl", "F1", "F2", "F3", "F4", "RightAlt", "RightShift", "Delete", "End" },
    Value    = "RightControl",
    Callback = function(v)
        local ok, kc = pcall(function() return Enum.KeyCode[v] end)
        if ok and kc then
            N("Toggle key", v)
        end
    end,
})

P_Set:Divider()
P_Set:Section("Toggle button shape")

P_Set:MultiButton({
    Title   = "Toggle button UICorner",
    Buttons = {
        { Text="Circle",  Callback=function() Library:SetToggleBtnCorner(UDim.new(1,0))  N("Shape","Circle")  end },
        { Text="Rounded", Callback=function() Library:SetToggleBtnCorner(UDim.new(0,8))  N("Shape","Rounded") end },
        { Text="Square",  Callback=function() Library:SetToggleBtnCorner(UDim.new(0,0))  N("Shape","Square")  end },
    },
})

P_Set:Button({
    Title    = "Change toggle button icon",
    Desc     = "Updates the floating UI toggle button",
    Text     = "Change",
    Callback = function() Library:SetToggleIcon("rbxassetid://104055321996495"); N("Icon","Updated") end,
})

P_Set:Divider()
P_Set:Section("Font")

local dropFont = P_Set:Dropdown({
    Title    = "UI Font",
    List     = { "Gotham", "GothamBold", "GothamMedium", "Montserrat", "Arial", "AvenirHeavy", "Highway" },
    Value    = "Gotham",
    Callback = function(v)
        local ok, f = pcall(function() return Enum.Font[v] end)
        if ok and f then
            Library:SetTheme({ Font=f, FontBold=f, FontMedium=f })
            N("Font", v)
        end
    end,
})

P_Set:Divider()
P_Set:Section("Header text")

P_Set:MultiButton({
    Buttons = {
        { Text="Set right title",  Callback=function() Library:SetExtraTitle("gooner"); Library:SetExtraSubTitle("detected") end },
        { Text="Clear right text", Callback=function() Library:SetExtraTitle(""); Library:SetExtraSubTitle("") end },
    },
})

P_Set:Divider()
P_Set:Section("Lock / Unlock")

P_Set:Paragraph({
    Title = "Lock covers the entire UI",
    Desc  = "Library:Lock() overlays every page. Nothing can be clicked. Library:Unlock() removes it.",
})

P_Set:MultiButton({
    Buttons = {
        { Text="Lock UI",   Color="#DC3232", Callback=function() Library:Lock() end },
        { Text="Unlock UI", Color="#50C864", Callback=function() Library:Unlock() end },
    },
})

P_Set:Divider()
P_Set:Section("Custom theme")

local themeAccent = P_Set:Input({ Title="Accent color (hex)", Placeholder="#FF007F", id="theme_accent" })
local themeTabStroke = P_Set:Input({ Title="Tab stroke (hex)", Placeholder="#4B0026", id="theme_tab_stroke" })
local themeCorner = P_Set:Slider({ Title="Corner radius", Min=0, Max=16, Value=5, Rounding=0, id="theme_corner" })

P_Set:MultiButton({
    Buttons = {
        { Text="Apply theme", Color="#50C864", Callback=function()
            local accent = themeAccent:GetValue()
            local tabstroke = themeTabStroke:GetValue()
            local corner = themeCorner:GetValue()
            local newTheme = {}
            if accent~="" then
                newTheme.Accent   = accent
                newTheme.TabImage = accent
            end
            if tabstroke~="" then newTheme.TabStroke = tabstroke end
            if corner then newTheme.CornerRadius = UDim.new(0, corner) end
            Library:SetTheme(newTheme)
            N("Theme applied", "Custom theme set", "#50C864")
        end },
        { Text="Save as config", Callback=function()
            local n = "theme_"..tostring(os.time())
            Cfg:addcfg(n)
            Cfg:updcfg(n)
            RefreshDrop()
            N("Saved", '"'..n..'"', "#50C864")
        end },
    },
})

P_Set:Divider()
P_Set:Section("Theme presets")

P_Set:MultiButton({
    Buttons = {
        { Text="Pink",   Callback=function() Library:SetTheme({Accent="#FF007F",TabImage="#FF007F",TabStroke="#4B0026"}) end },
        { Text="Blue",   Color="#0088FF", Callback=function() Library:SetTheme({Accent="#0088FF",TabImage="#0088FF",TabStroke="#003366"}) end },
        { Text="Green",  Color="#00CC66", Callback=function() Library:SetTheme({Accent="#00CC66",TabImage="#00CC66",TabStroke="#004D26"}) end },
        { Text="Purple", Color="#9955FF", Callback=function() Library:SetTheme({Accent="#9955FF",TabImage="#9955FF",TabStroke="#330066"}) end },
    },
})

P_Set:Divider()
P_Set:Section("Notification tests")

P_Set:MultiButton({
    Buttons = {
        { Text="Info",    Color="#6495ED", Callback=function() N("Info",    "Something to note",     "#6495ED",4) end },
        { Text="Success", Color="#50C864", Callback=function() N("Success", "<b>Done</b>",            "#50C864",4) end },
        { Text="Warning", Color="#FFA500", Callback=function() N("Warning", "Check <i>this</i>",      "#FFA500",4) end },
        { Text="Error",   Color="#DC3232", Callback=function() N("Error",   "Something broke",        "#DC3232",4) end },
    },
})

P_Set:MultiButton({
    Buttons = {
        { Text="With icon", Callback=function()
            Library:Notification({ Title="Notification", Desc="Has an icon", Color="#FF007F", Duration=3, Icon="rbxassetid://104055321996495" })
        end },
        { Text="Long one", Callback=function()
            Library:Notification({ Title="Long notification", Desc="This one has a longer description that wraps to multiple lines to test the layout", Color="#9955FF", Duration=5 })
        end },
    },
})

N("<b>Skid Playground</b>", Exec.name.."  ·  RCtrl to toggle", "#FF007F", 5)
